### PR TITLE
Interface marclab script with multinet instance

### PR DESCRIPTION
**Pull request by jjnesbitt**
~~Depends on https://github.com/multinet-app/multinet-api/pull/35.~~

After testing locally with the changes included in the above dependent API PR, it seems to perform as expected. The script will completely remove the existing tables/networks, and upload them from scratch, using the result from running `marclab.py`.

Creating as a draft because more collaboration with @gotdairyya may be required before this is good to go.

### CODE REVIEW

**Comment by jjnesbitt** [comment]
This PR now depends on https://github.com/multinet-app/multinet-api/pull/45. Once that is merged, I believe this will behave as expected.

**Comment by waxlamp** [comment]
> This PR now depends on [multinet-app/multinet-api#45](https://github.com/multinet-app/multinet-api/pull/45). Once that is merged, I believe this will behave as expected.

Can you give a status update on this? I see I'm named as a reviewer but I don't think I have enough context to review at the moment (including the relationship between this PR and multinet-app/multinet-api#45, which has now been merged).

**Comment by jjnesbitt** [comment]
> Can you give a status update on this?

As far as I'm concerned this is complete. The script works (just tested), and everything is set in the api. If you don't have any comments/concerns I can merge it.

**Review by waxlamp — APPROVED** [review]

**Comment by waxlamp** [comment]
> > Can you give a status update on this?
> 
> As far as I'm concerned this is complete. The script works (just tested), and everything is set in the api. If you don't have any comments/concerns I can merge it.

No objections. Nice work!

**Pull request merged**
